WebApp/WebApp/Controllers/DoctorController.cs
using AutoMapper;
using Common.Interfaces;
using DAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebApp.Models.DoctorModels;

namespace WebApp.Controllers
{
    public class DoctorController : BaseController
    {
        private readonly IDoctorRepo _doctorRepo;
        private readonly ILogger<DoctorController> _logger;

        public DoctorController(IDoctorRepo doctorRepo, ILogger<DoctorController> logger)
        {
            _doctorRepo = doctorRepo;
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInfo($"Zapytanie do metody Index()");

            DisplayErrorFromRedirectIfNecessary();

            var result = _doctorRepo.Get();

            if (!result.IsSuccess)
            {
                AddLocalError(result.FailureMessage);
                return View(Enumerable.Empty<DoctorViewModel>());
            }

            var model = Mapper.Map<IEnumerable<DoctorViewModel>>(result.Value);

            return View(model);
        }

        public IActionResult Delete(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Delete()", new { id });

            var result = _doctorRepo.Remove(id);

            if (result.IsSuccess) return RedirectToIndex();

            return RedirectToIndex(result.FailureMessage);
        }

        public IActionResult Create()
        {
            _logger.LogInfo($"Zapytanie do metody Create()");

            var model = new DoctorViewModel
            {
                HasValidMedicalLicense = true,
                RowVersion = 1
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(DoctorViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Create()", new { model });

            if (!ModelState.IsValid) return View(model);

            var entity = Mapper.Map<Doctor>(model);
            var result = _doctorRepo.Add(entity);

            if (result.IsSuccess) return RedirectToIndex();

            AddLocalError(result.FailureMessage);
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Edit()", new { id });

            DisplayErrorFromRedirectIfNecessary();

            var result = _doctorRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            var model = Mapper.Map<DoctorViewModel>(result.Value);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(DoctorViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Edit()", new { model });

            if (!ModelState.IsValid) return View(model);

            var entity = Mapper.Map<Doctor>(model);
            var result = _doctorRepo.Edit(entity);

            if (result.IsSuccess) return RedirectToAction("Details", new { id = model.Id }); ;

            AddErrorForRedirect(result.FailureMessage);
            return RedirectToAction(nameof(Edit), new { id = model.Id});
        }

        public IActionResult RemoveLicesnse(int id)
        {
            _logger.LogInfo($"Zapytanie do metody RemoveLicesnse()", new { id });

            var result = _doctorRepo.RemoveLicence(id);

            if (result.IsSuccess) return RedirectToIndex();

            return RedirectToIndex(result.FailureMessage);
        }

        public IActionResult Details(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Details()", new { id });

            var result = _doctorRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            var model = Mapper.Map<DoctorViewModel>(result.Value);

            return View(model);
        }
    }
}

WebApp/WebApp/Controllers/LoggerController.cs
using Common.Interfaces;
using Common.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using static Common.Handlers.StaticDatabaseExceptionHandler;

namespace WebApp.Controllers
{
    public class LoggerController : BaseController
    {
        private readonly ILogger<LoggerController> _logger;

        public LoggerController(ILogger<LoggerController> logger)
        {
            _logger = logger;
        }

        public IActionResult Errors()
        {
            DisplayErrorFromRedirectIfNecessary();

            var errors = Try(() => 
            {
                return _logger.ErrorLogs();
            }, typeof(LoggerController));

            if (errors.IsSuccess) return View(errors.Value);

            AddLocalError(errors.FailureMessage);
            return View(Enumerable.Empty<ErrorLogModel>());
        }

        public IActionResult Infos()
        {
            DisplayErrorFromRedirectIfNecessary();

            var infos = Try(() =>
            {
                return _logger.InfoLogs();
            }, typeof(LoggerController));

            if (infos.IsSuccess) return View(infos.Value);

            AddLocalError(infos.FailureMessage);
            return View(Enumerable.Empty<BaseLogModel>());
        }

        public IActionResult ErrorDetails(string objectId)
        {
            var info = Try(() =>
            {
                return _logger.GetErrorLog(objectId);
            }, typeof(LoggerController));

            if (info.IsSuccess) return View(info.Value);

            AddErrorForRedirect(info.FailureMessage);
            return RedirectToAction(nameof(Errors));
        }

        public IActionResult InfoDetails(string objectId)
        {
            var info = Try(() =>
            {
                return _logger.GetInfoLog(objectId);
            }, typeof(LoggerController));

            if (info.IsSuccess) return View(info.Value);

            AddErrorForRedirect(info.FailureMessage);
            return RedirectToAction(nameof(Infos));
        }

        public IActionResult ClearAllInfo()
        {
            _logger.ClearAllInfoLogs();

            return RedirectToAction(nameof(Infos));
        }

        public IActionResult ClearAllError()
        {
            _logger.ClearAllErrorLogs();

            return RedirectToAction(nameof(Errors));
        }

        public IActionResult DeleteError(string objectId)
        {
            _logger.RemoveErrorLog(objectId);

            return RedirectToAction(nameof(Errors));
        }

        public IActionResult DeleteInfo(string objectId)
        {
            _logger.RemoveInfoLog(objectId);

            return RedirectToAction(nameof(Infos));
        }
    }
}

WebApp/WebApp/Controllers/MedicineController.cs
using AutoMapper;
using Common.Interfaces;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebApp.Models.MedicineModels;

namespace WebApp.Controllers
{
    public class MedicineController : BaseController
    {
        private readonly IMedicineRepo _medicineRepo;
        public readonly ILogger<MedicineController> _logger;

        public MedicineController(IMedicineRepo medicineRepo, ILogger<MedicineController> logger)
        {
            _medicineRepo = medicineRepo;
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInfo($"Zapytanie do metody Index()");

            DisplayErrorFromRedirectIfNecessary();

            var result = _medicineRepo.Get();

            if (!result.IsSuccess)
            {
                AddLocalError(result.FailureMessage);
                return View(Enumerable.Empty<MedicineViewModel>());
            }

            var model = Mapper.Map<IEnumerable<MedicineViewModel>>(result.Value);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            _logger.LogInfo($"Zapytanie do metody Create()");

            var model = new CreateMedicineViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CreateMedicineViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Create(model)", new { model });

            if (!ModelState.IsValid) return View(model);

            var result = _medicineRepo.Add(model);

            if (result.IsSuccess) return RedirectToIndex();

            return RedirectToIndex(result.FailureMessage);
        }

        public IActionResult Details(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Details(id)", new { id });

            var result = _medicineRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return View((MedicineDetailsViewModel)result.Value);
        }

        public IActionResult Delete(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Delete(id)", new { id });

            var result = _medicineRepo.Delete(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return RedirectToIndex();
        }

        public IActionResult MakeExpired(int id)
        {
            _logger.LogInfo($"Zapytanie do metody MakeExpired(id)", new { id });

            var result = _medicineRepo.MakeExpired(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return RedirectToIndex();
        }
    }
}

WebApp/WebApp/Controllers/OrderController.cs
using Common.Interfaces;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebApp.Interfaces;
using WebApp.Models.OrderModels;
using static AutoMapper.Mapper;

namespace WebApp.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IApothecaryRepo _apothecaryRepo;
        private readonly IOrderRepo _orderRepo;
        private readonly IMedicineRepo _medicineRepo;
        private readonly ILogger<OrderController> _logger;
        private readonly ISelectService _selectService;

        public OrderController(IApothecaryRepo apothecaryRepo,
            IOrderRepo orderRepo,
            IMedicineRepo medicineRepo,
            ILogger<OrderController> logger,
            ISelectService selectService)
        {
            _apothecaryRepo = apothecaryRepo;
            _orderRepo = orderRepo;
            _medicineRepo = medicineRepo;
            _logger = logger;
            _selectService = selectService;
        }

        public IActionResult Index()
        {
            _logger.LogInfo($"Zapytanie do metody Index()");

            DisplayErrorFromRedirectIfNecessary();

            var result = _orderRepo.Get();

            if (result.IsSuccess)
            {
                var model = Map<IEnumerable<OrderViewModel>>(result.Value);
                return View(model);
            }
            else
            {
                AddLocalError(result.FailureMessage);
                return View(Enumerable.Empty<OrderViewModel>());
            }
        }

        public IActionResult Details(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Details(id)", new { id });

            DisplayErrorFromRedirectIfNecessary();

            var result = _orderRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            var order = Map<OrderDetailViewModel>(result.Value);
            return View(order);
        }

        [HttpGet]
        public IActionResult Create()
        {
            _logger.LogInfo($"Zapytanie do metody Create()");

            var result = _selectService.GetApothecarySelectList();

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage); 

            var model = new CreateOrderViewModel
            {
                ApothecaryList = result.Value
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CreateOrderViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Create(model)", new { model });

            if (!ModelState.IsValid) return View(model);

            var result = _orderRepo.Create(model.SelectedId);

            if (result.IsSuccess) return RedirectToDetails(result.Value);

            return RedirectToIndex(result.FailureMessage);
        }

        public IActionResult SendOrder(int orderId)
        {
            _logger.LogInfo($"Zapytanie do metody SendOrder(orderId)", new { orderId });

            var result = _orderRepo.SendOrder(orderId);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return RedirectToIndex();
        }

        public IActionResult AddOrderItem(int orderId)
        {
            _logger.LogInfo($"Zapytanie do metody AddOrderItem(orderId)", new { orderId });

            var result = _selectService.GetMedicineSelectList();

            if (!result.IsSuccess) return RedirectToDetails(orderId, result.FailureMessage);

            var model = new AddOrderItemViewModel
            {
                OrderId = orderId,
                MedicineList = result.Value
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddOrderItem(AddOrderItemViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody AddOrderItem(model)", new { model });

            var medicineListResult = _selectService.GetMedicineSelectList();

            if (!medicineListResult.IsSuccess)
                return RedirectToDetails(model.OrderId, medicineListResult.FailureMessage);

            if (!ModelState.IsValid)
            {
                model.MedicineList = medicineListResult.Value;
                return View(model);
            }

            var result = _orderRepo.AddOrderItem(model.OrderId, model);

            if (!result.IsSuccess) AddErrorForRedirect(result.FailureMessage);

            return RedirectToDetails(model.OrderId);
        }

        public IActionResult Delete(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Delete(id)", new { id });

            var result = _orderRepo.RemoveOrder(id);

            if (result.IsSuccess) return RedirectToIndex();

            return RedirectToIndex(result.FailureMessage);
        }

        [HttpGet]
        public IActionResult EditOrderItem(int orderId, int itemId)
        {
            _logger.LogInfo($"Zapytanie do metody EditOrderItem(orderId, itemId)", new { orderId, itemId });

            var result = _orderRepo.Get(orderId);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            var item = result.Value.OrderItems.FirstOrDefault(i => i.Id == itemId);

            if (item == null) return RedirectToDetails(orderId, $"Nie znaleziono pozycji na zamówieniu o Id {itemId}");

            return View((EditOrderItemViewModel)item);
        }

        [HttpPost]
        public IActionResult EditOrderItem(EditOrderItemViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody EditOrderItem(model)", new { model });

            if (!ModelState.IsValid) return View(model);

            var result = _orderRepo.EditOrderItem(model);

            if (!result.IsSuccess) return RedirectToDetails(model.OrderId, result.FailureMessage);

            return RedirectToDetails(model.OrderId);
        }

        public IActionResult DeleteOrderItem(int orderId, int itemId)
        {
            _logger.LogInfo($"Zapytanie do metody DeleteOrderItem(orderId, itemId)", new { orderId, itemId });

            var result = _orderRepo.DeleteOrderItem(orderId, itemId);

            if (!result.IsSuccess) return RedirectToDetails(orderId, result.FailureMessage);

            return RedirectToDetails(orderId);
        }

        private IActionResult RedirectToDetails(int orderId) => RedirectToDetails(orderId, null);

        private IActionResult RedirectToDetails(int orderId, string errorMsg)
        {
            if (!string.IsNullOrEmpty(errorMsg)) AddErrorForRedirect(errorMsg);
            return RedirectToAction(nameof(Details), new { id = orderId });
        }
    }
}

WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iDrugs</title>

    <environment include="Development">
        
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Apteka - iDrugs</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li><a asp-area="" asp-controller="Home" asp-action="Index">Strona domowa</a></li>-->
                    <li><a asp-area="" asp-controller="Apothecary" asp-action="Index">Aptekarze</a></li>
                    <li><a asp-area="" asp-controller="Prescription" asp-action="Index">Recepty</a></li>
                    <li><a asp-area="" asp-controller="Medicine" asp-action="Index">Spis leków</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Index">Zamówienia</a></li>
                    <li><a asp-area="" asp-controller="Warehouse" asp-action="Index">Hurtownia</a></li>
                    <li><a asp-area="" asp-controller="Doctor" asp-action="Index">Spis Lekarzy</a></li>
                    <li><a asp-area="" asp-controller="DrugStoreStock" asp-action="Index">Stan leków w aptece</a></li>
                    <li><a asp-area="" asp-controller="Statistic" asp-action="Index">Statystyki</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Logi<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Logger" asp-action="Errors">Błędy</a></li>
                            <li><a asp-area="" asp-controller="Logger" asp-action="Infos">Informacje</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @if (!string.IsNullOrEmpty(ViewBag.ErrorMsg))
        {
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>@ViewBag.ErrorMsg</strong>
            </div>
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - iDrugs</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>