WebApp/WebApp/Controllers/ApothecaryController.cs
using Common.Interfaces;
using Common.Utils;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebApp.Models.ApothecaryModels;
using WebApp.Models.PrescriptionModels;

namespace WebApp
{
    public class ApothecaryController : BaseController
    {
        private readonly IApothecaryRepo _repo;
        private readonly ILogger<ApothecaryController> _logger;

        public ApothecaryController(IApothecaryRepo repo, ILogger<ApothecaryController> logger)
        {
            _repo = repo;
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInfo($"Zapytanie do metody Index()");

            ViewBag.ErrorMsg = string.Empty;
            if (TempData.ContainsKey("ErrorMsg"))
            {
                ViewBag.ErrorMsg = TempData["ErrorMsg"];
                TempData.Remove("ErrorMsg");
            }

            var result = _repo.Get();

            if(!result.IsSuccess)
            {
                ViewBag.ErrorMsg = result.FailureMessage;
                return View(new ApothecaryViewModel[] { });
            }
            else
            {
                var apothecaries = result.Value.Select(x => (ApothecaryViewModel)x);
                return View(apothecaries);
            }
        }

        public IActionResult Add()
        {
            _logger.LogInfo($"Zapytanie do metody Add()");
            return View();
        }

        [HttpPost]
        public IActionResult Add(ApothecaryViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Add(model)", new { model });

            if (!ModelState.IsValid) return View(model);

            var result = _repo.Add(model);

            if (result.IsSuccess) return RedirectToAction("Index");
            else
            {
                ViewBag.ErrorMsg = result.FailureMessage;
                return View(model);
            }
        }

        public IActionResult Fire(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Fire(id)", new { id });

            var result = _repo.Fire(id);
            var errorMsg = string.Empty;
            if (!result.IsSuccess) errorMsg = result.FailureMessage;

            return RedirectToIndex(errorMsg);
        }

        public IActionResult Details(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Details(id)", new { id });

            var result = _repo.Get(id);

            if (result.IsSuccess)
            {
                return View((ApothecaryViewModel)result.Value);
            }
            else
            {
                return RedirectToIndex($"Nie ma aptekarza o id {id}");
            }
        }

        public IActionResult Edit(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Edit(id)", new { id });

            DisplayErrorFromRedirectIfNecessary();

            var result = _repo.Get(id);
            if (result.IsSuccess)
            {
                return View((ApothecaryViewModel)result.Value);
            }
            else
            {
                return RedirectToIndex(result.FailureMessage);
            }
        }

        [HttpPost]
        public IActionResult Edit(ApothecaryViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Edit(model)", new { model });

            if (!ModelState.IsValid) return View(model);

            var result = _repo.Update(model);

            if (result.IsSuccess)
            {
                return RedirectToAction("Details", new { id = result.Value.Id});
            }
            else
            {
                AddErrorForRedirect(result.FailureMessage);
                return RedirectToAction("Edit", new { id = model.Id });
            }
        }

        public IActionResult Delete(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Delete(id)", new { id });

            var result = _repo.Remove(id);
            var errorMsg = string.Empty;

            if (!result.IsSuccess) errorMsg = result.FailureMessage;

            return RedirectToIndex(errorMsg);
        }
    }
}

WebApp/WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            var dbContext = new DAL.iDrugsEntities();
            dbContext.SaveChanges();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/WebApp/Controllers/MedicineController.cs
using AutoMapper;
using Common.Interfaces;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebApp.Models.MedicineModels;

namespace WebApp.Controllers
{
    public class MedicineController : BaseController
    {
        private readonly IMedicineRepo _medicineRepo;
        public readonly ILogger<MedicineController> _logger;

        public MedicineController(IMedicineRepo medicineRepo, ILogger<MedicineController> logger)
        {
            _medicineRepo = medicineRepo;
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInfo($"Zapytanie do metody Index()");

            DisplayErrorFromRedirectIfNecessary();

            var result = _medicineRepo.Get();

            if (!result.IsSuccess)
            {
                AddLocalError(result.FailureMessage);
                return View(Enumerable.Empty<MedicineViewModel>());
            }

            var model = Mapper.Map<IEnumerable<MedicineViewModel>>(result.Value);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            _logger.LogInfo($"Zapytanie do metody Create()");

            var model = new CreateMedicineViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CreateMedicineViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Create(model)", new { model });

            if (!ModelState.IsValid) return View(model);

            var result = _medicineRepo.Add(model);

            if (result.IsSuccess) return RedirectToIndex();

            return RedirectToIndex(result.FailureMessage);
        }

        public IActionResult Details(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Details(id)", new { id });

            var result = _medicineRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return View((MedicineDetailsViewModel)result.Value);
        }

        public IActionResult Delete(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Delete(id)", new { id });

            var result = _medicineRepo.Delete(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return RedirectToIndex();
        }

        public IActionResult MakeExpired(int id)
        {
            _logger.LogInfo($"Zapytanie do metody MakeExpired(id)", new { id });

            var result = _medicineRepo.MakeExpired(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return RedirectToIndex();
        }
    }
}

WebApp/WebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApp/WebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApp/WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Strona domowa";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/medicine.svg" alt="Leki" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Sprawdź aktualny spis leków
                    <a class="btn btn-default" asp-controller="Medicine" asp-action="Index">
                        Spis leków
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/apothecaries.svg" alt="Aptekarze" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Poznaj naszych pracowników
                    <a class="btn btn-default" asp-controller="Apothecary" asp-action="Index">
                        Aptekarze
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-12">
        <h1 class="text text-center">Witaj w systemie zarzadzania apteką iDrugs</h1>
    </div>      
</div>