WebApp/WebApp/Controllers/WarehouseController.cs
using AutoMapper;
using Common.Interfaces;
using Common.Utils;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using WebApp.Models.MedicineModels;
using WebApp.Models.WarehouseModels;
using static AutoMapper.Mapper;
using static Common.Handlers.StaticDatabaseExceptionHandler;

namespace WebApp.Controllers
{
    public class WarehouseController : BaseController
    {
        private readonly IWarehouseRepo _warehouseRepo;
        private readonly IMedicineRepo _medicineRepo;
        private readonly ILogger<WarehouseController> _logger;

        public WarehouseController(IWarehouseRepo warehouseRepo, IMedicineRepo medicineRepo, ILogger<WarehouseController> logger)
        {
            _warehouseRepo = warehouseRepo;
            _medicineRepo = medicineRepo;
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInfo($"Zapytanie do metody Index()");

            DisplayErrorFromRedirectIfNecessary();

            var result = _warehouseRepo.Get();

            if (result.IsSuccess)
            {
                var model = Mapper.Map<IEnumerable<WarehouseItemViewModel>>(result.Value);
                return View(model);
            }

            AddLocalError(result.FailureMessage);
            return View(Enumerable.Empty<WarehouseItemViewModel>());
        }

        public IActionResult Create()
        {
            _logger.LogInfo($"Zapytanie do metody Create()");

            var model = new AddWarehouseItemViewModel
            {
                MedicineList = GetMedicineSelectList().Value
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(AddWarehouseItemViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Create(model)", new { model });

            if (!ModelState.IsValid)
            {
                model.MedicineList = GetMedicineSelectList().Value;
                return View(model);
            }
            var entity = Map<WarehouseItemViewModel>(model);

            _warehouseRepo.Add(entity);

            return RedirectToIndex();
        }

        public IActionResult Edit(int id)
        {
            _logger.LogInfo($"Zapytanie do metody Edit(id)", new { id });

            var result = _warehouseRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            var model = Map<AddWarehouseItemViewModel>((WarehouseItemViewModel)result.Value);

            model.MedicineList = GetMedicineSelectList().Value;
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(AddWarehouseItemViewModel model)
        {
            _logger.LogInfo($"Zapytanie do metody Edit(model)", new { model });

            if (!ModelState.IsValid)
            {
                model.MedicineList = GetMedicineSelectList().Value;
                return View(model);
            }

            var result = _warehouseRepo.Add(Map<WarehouseItemViewModel>(model));

            if (!result.IsSuccess)
            {
                AddLocalError(result.FailureMessage);
                return View(model);
            }

            return RedirectToIndex();
        }

        private Result<IEnumerable<MedicineSelectModel>> GetMedicineSelectList()
        {
            return Try(() =>
            {
                var result = _medicineRepo.Get();

                if (!result.IsSuccess) throw new Exception(result.FailureMessage);

                var temp = Map<IEnumerable<MedicineViewModel>>(result.Value);
                return Map<IEnumerable<MedicineSelectModel>>(temp);
            }, typeof(WarehouseController));
        }
    }
}

WebApp/WebApp/Views/Warehouse/Create.cshtml
@using WebApp.Models.WarehouseModels
@model AddWarehouseItemViewModel

@{
    ViewData["Title"] = "Utwórz";
}

<h2>Dodaj lub zmień lek w hurtowni</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MedicineId" class="control-label"></label>
                <select asp-for="MedicineId" class="form-control selectpicker" data-live-search="true"
                        asp-items="@{new SelectList(Model.MedicineList, "Id", "FullName")}"></select>
                <span asp-validation-for="MedicineId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<button onclick="location.href='@Url.Action("Index","Warehouse")'"
        class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span>
    <span>Powrót</span>
</button>

WebApp/WebApp/Views/Warehouse/Edit.cshtml
@model WebApp.Models.WarehouseModels.AddWarehouseItemViewModel

@{
    ViewData["Title"] = "Edycja pozycji w hurtowni";
}

<h2>Edycja pozycji w hurtowni</h2>

<h4>Nowa ilość leku @Model.MedicineList.First(x => x.Id == Model.MedicineId).FullName w hurtowni</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="MedicineId" class="form-control" />
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-save"></span>
                    <span>Zapisz</span>
                </button>
            </div>
        </form>
    </div>
</div>

<button onclick="location.href='@Url.Action("Index","Warehouse")'"
        class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span>
    <span>Powrót</span>
</button>

WebApp/WebApp/Views/Warehouse/Index.cshtml
@using WebApp.Models.WarehouseModels;
@model IEnumerable<WarehouseItemViewModel>

@{
    ViewData["Title"] = "Hurtownia";
}

<h2>Hurtownia leków</h2>

<button onclick="location.href='@Url.Action("Create","Warehouse")'"
        class="btn btn-default">
    <span class="glyphicon glyphicon-plus"></span>
    <span>Dodaj/zmień ilość leków w hurtowni</span>
</button>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Medicine.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicine.MedicineContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Medicine.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Medicine.MedicineContent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    <button onclick="location.href='@Url.Action("Edit","Warehouse", new { id = item.Id })'"
                            class="btn btn-default">
                        <span class="glyphicon glyphicon-edit"></span>
                        <span>Edytuj</span>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>