WebApp/WebApp/Models/PrescriptionModels/AddPrescriptionItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models.DoctorModels;
using WebApp.Models.MedicineModels;

namespace WebApp.Models.PrescriptionModels
{
    public class AddPrescriptionItemViewModel : PrescriptionItemViewModel
    {
        [Display(Name = "Lek")]
        public IEnumerable<MedicineSelectModel> MedicineList { get; set; }
    }
}

WebApp/WebApp/Models/PrescriptionModels/CreatePrescriptionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models.ApothecaryModels;
using WebApp.Models.DoctorModels;

namespace WebApp.Models.PrescriptionModels
{
    public class CreatePrescriptionViewModel : PrescriptionViewModel
    {
        [Display(Name = "Doktor wydający receptę")]
        public IEnumerable<DoctorSelectViewModel> DoctorSelect { get; set; }

        [Display(Name = "Aptekarz dodający receptę")]
        public IEnumerable<ApothecarySelectViewModel> ApothecarySelect { get; set; }
    }
}

WebApp/WebApp/Models/PrescriptionModels/PrescriptionViewModel.cs
using Common.Utils;
using DAL;
using System.Linq;
using DAL.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebApp.Models.ApothecaryModels;
using WebApp.Models.DoctorModels;
using static AutoMapper.Mapper;

namespace WebApp.Models.PrescriptionModels
{
    public class PrescriptionViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "ID Lekarza")]
        public int DoctorId { get; set; }

        [Display(Name = "Lekarz")]
        public string DoctorFullName { get; set; }

        [Display(Name = "ID Aptekarza")]
        public int ApothecaryId { get; set; }

        [Display(Name = "Aptekarz")]
        public string ApothecaryFullName { get; set; }

        [Display(Name = "Data przepisania")]
        [DisplayFormat(DataFormatString = "{0:dd MMMM yyyy}")]
        [DataType(DataType.Date)]
        public DateTime PrescriptionDate { get; set; }

        [Display(Name = "Data wykupienia")]
        [DisplayFormat(DataFormatString = "{0:dd MMMM yyyy}")]
        public DateTime? CompletionDate { get; set; }

        [Display(Name = "Status recepty")]
        public PrescriptionStatusEnum Status { get; set; }
        public string StatusString { get => Status.GetDisplayName(); }

        [Display(Name = "Całkowity koszt")]
        [DisplayFormat(DataFormatString = "{0:0.00} zł")]
        public decimal TotalCost { get; set; }

        [Display(Name = "Pozostały koszt")]
        [DisplayFormat(DataFormatString = "{0:0.00} zł")]
        public decimal RemainingCost { get => PrescriptionItems?.Sum(x => x.RemainingCost) ?? 0; }

        [Display(Name = "Email klienta")]
        public string Email { get; set; }

        [Display(Name = "Wersja")]
        public int RowVersion { get; set; }

        [Display(Name = "Aptekarz")]
        public virtual ApothecaryViewModel Apothecary { get; set; }

        [Display(Name = "Lekarz")]
        public DoctorViewModel Doctor { get; set; }

        [Display(Name = "Leki na recepcie")]
        public IEnumerable<PrescriptionItemViewModel> PrescriptionItems { get; set; }

        public static implicit operator Prescription(PrescriptionViewModel model)
        {
            return Map<Prescription>(model);
        }

        public static implicit operator PrescriptionViewModel(Prescription entity)
        {
            return Map<PrescriptionViewModel>(entity);
        }
    }
}

WebApp/WebApp/Controllers/PrescriptionController.cs
using AutoMapper;
using Common.Interfaces;
using Common.Utils;
using DAL.Enums;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using WebApp.Interfaces;
using WebApp.Models.PrescriptionModels;

namespace WebApp.Controllers
{
    public class PrescriptionController : BaseController
    {
        #region Properties
        private readonly IPrescriptionRepo _prescriptionRepo;
        private readonly ILogger<PrescriptionController> _logger;
        private readonly ISelectService _selectService;
        private readonly IDrugStoreStockRepo _drugStoreStockRepo;
        private readonly IEmailSenderService _emailSenderService;

        public PrescriptionController(IPrescriptionRepo prescriptionRepo, ILogger<PrescriptionController> logger, ISelectService selectService, IDrugStoreStockRepo drugStoreStockRepo, IEmailSenderService emailSenderService)
        {
            _prescriptionRepo = prescriptionRepo;
            _logger = logger;
            _selectService = selectService;
            _drugStoreStockRepo = drugStoreStockRepo;
            _emailSenderService = emailSenderService;
        }

        #endregion


        public IActionResult Index()
        {
            DisplayErrorFromRedirectIfNecessary();

            var result = _prescriptionRepo.Get();

            if (result.IsSuccess)
            {
                var model = new IndexViewModel
                {
                    Prescriptions = Mapper.Map<IEnumerable<PrescriptionViewModel>>(result.Value)
                };
                return View(model);
            }

            AddLocalError(result.FailureMessage);
            return View(Enumerable.Empty<PrescriptionViewModel>());
        }

        [HttpPost]
        public IActionResult Search(IndexViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToIndex("Proszę podać wartość liczbową do wyszukiwania");

            if (!model.SearchId.HasValue) return RedirectToIndex();

            return RedirectToAction(nameof(PrescriptionDetails), new { id = model.SearchId.Value });
        }

        public IActionResult CreatePrescription()
        {
            var doctors = _selectService.GetDoctorSelectList();
            var apothecaries = _selectService.GetApothecarySelectList();

            if (!doctors.IsSuccess) return RedirectToIndex(doctors.FailureMessage);
            if (!apothecaries.IsSuccess) return RedirectToIndex(apothecaries.FailureMessage);

            var model = new CreatePrescriptionViewModel
            {
                ApothecarySelect = apothecaries.Value,
                DoctorSelect = doctors.Value,
                PrescriptionDate = DateTime.Now
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult CreatePrescription(CreatePrescriptionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var action = AddSelectListToModelWithRedirectToIndex(model);
                return action ?? View(model);
            }

            var result = _prescriptionRepo.AddPrescription(model);

            if (!result.IsSuccess)
            {
                AddLocalError(result.FailureMessage);
                var action = AddSelectListToModelWithRedirectToIndex(model);
                return action ?? View(model);
            }

            return RedirectToPrescriptionDetails(result.Value);
        }

        private IActionResult AddSelectListToModelWithRedirectToIndex(CreatePrescriptionViewModel model)
        {
            var doctors = _selectService.GetDoctorSelectList();
            var apothecaries = _selectService.GetApothecarySelectList();

            if (!doctors.IsSuccess) return RedirectToIndex(doctors.FailureMessage);
            if (!apothecaries.IsSuccess) return RedirectToIndex(apothecaries.FailureMessage);

            model.ApothecarySelect = apothecaries.Value;
            model.DoctorSelect = doctors.Value;

            return null;
        }

        public IActionResult PrescriptionDetails(int id)
        {
            DisplayErrorFromRedirectIfNecessary();

            var result = _prescriptionRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            var model = Mapper.Map<PrescriptionViewModel>(result.Value);
            return View(model);
        }

        public IActionResult EditPrescription(int id)
        {
            DisplayErrorFromRedirectIfNecessary();

            var doctors = _selectService.GetDoctorSelectList();
            var apothecaries = _selectService.GetApothecarySelectList();
            var result = _prescriptionRepo.Get(id);

            if (!doctors.IsSuccess) return RedirectToPrescriptionDetails(id, doctors.FailureMessage);
            if (!apothecaries.IsSuccess) return RedirectToPrescriptionDetails(id, apothecaries.FailureMessage);
            if (!result.IsSuccess) return RedirectToPrescriptionDetails(id, result.FailureMessage);

            var model = Mapper.Map<CreatePrescriptionViewModel>(result.Value);

            if (model.Status != PrescriptionStatusEnum.Created)
                return RedirectToPrescriptionDetails(id, $"Nie można modyfikować recepty o statusie {model.Status.GetDisplayName()}");

            model.ApothecarySelect = apothecaries.Value;
            model.DoctorSelect = doctors.Value;

            return View(model);
        }

        public IActionResult AcceptPrescription(int id)
        {

            var result = _prescriptionRepo.AcceptCreated(id);
            var emailResult = _prescriptionRepo.Get(id);

            if (!result.IsSuccess) return RedirectToPrescriptionDetails(id, result.FailureMessage);
            if (!emailResult.IsSuccess) return RedirectToPrescriptionDetails(id, result.FailureMessage);

            var emailMsg = result.Value;
            var email = emailResult.Value.Email;

            _emailSenderService.SendEmail(email, "Rejestracja recepty", emailMsg);

            return RedirectToPrescriptionDetails(id);
        }

        [HttpPost]
        public IActionResult EditPrescription(CreatePrescriptionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var action = AddSelectListToModelWithRedirectToDetails(model);
                return action ?? View(model);
            }

            var result = _prescriptionRepo.EditPrescription(model);

            if (!result.IsSuccess)
            {
                AddLocalError(result.FailureMessage);
                var action = AddSelectListToModelWithRedirectToDetails(model);
                return action ?? RedirectToAction(nameof(EditPrescription), new { id = model.Id });
            }

            return RedirectToPrescriptionDetails(model.Id);
        }

        private IActionResult AddSelectListToModelWithRedirectToDetails(CreatePrescriptionViewModel model)
        {
            var doctors = _selectService.GetDoctorSelectList();
            var apothecaries = _selectService.GetApothecarySelectList();

            if (!doctors.IsSuccess) return RedirectToPrescriptionDetails(model.Id, doctors.FailureMessage);
            if (!apothecaries.IsSuccess) return RedirectToPrescriptionDetails(model.Id, apothecaries.FailureMessage);

            model.ApothecarySelect = apothecaries.Value;
            model.DoctorSelect = doctors.Value;

            return null;
        }

        public IActionResult AddPrescriptionItem(int id)
        {
            var result = _prescriptionRepo.Get(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);
            var prescription = (PrescriptionViewModel)result.Value;
            if (prescription.Status != PrescriptionStatusEnum.Created)
                return RedirectToPrescriptionDetails(id, $"Nie można dodać leku do recepty o statusie: {prescription.Status.GetDisplayName()}");

            var model = new AddPrescriptionItemViewModel { PrescriptionId = id };

            var action = AddSelectListToModelWithRedirectToDetails(model);

            return action ?? View(model);
        }

        [HttpPost]
        public IActionResult AddPrescriptionItem(AddPrescriptionItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var action = AddSelectListToModelWithRedirectToDetails(model);
                return action ?? View(model);
            }

            var result = _prescriptionRepo.AddPrescriptionItem(model.PrescriptionId, model);

            if (!result.IsSuccess) AddErrorForRedirect(result.FailureMessage);

            return RedirectToPrescriptionDetails(model.PrescriptionId);
        }

        private IActionResult AddSelectListToModelWithRedirectToDetails(AddPrescriptionItemViewModel model)
        {
            var medicine = _selectService.GetMedicineSelectList();

            if (!medicine.IsSuccess) return RedirectToPrescriptionDetails(model.Id, medicine.FailureMessage);

            model.MedicineList = medicine.Value;

            return null;
        }

        public IActionResult DeletePrescription(int id)
        {
            var result = _prescriptionRepo.DeletePrescription(id);

            if (!result.IsSuccess) return RedirectToIndex(result.FailureMessage);

            return RedirectToIndex();
        }

        public IActionResult RemovePrescriptionItem(int prescriptionId, int itemId)
        {
            var result = _prescriptionRepo.DeletePrescriptionItem(prescriptionId, itemId);

            if (!result.IsSuccess) AddErrorForRedirect(result.FailureMessage);

            return RedirectToPrescriptionDetails(prescriptionId);
        }

        public IActionResult EditPrescriptonItem(int prescriptionId, int itemId)
        {
            DisplayErrorFromRedirectIfNecessary();

            var result = _prescriptionRepo.GetItem(itemId);

WebApp/WebApp/Views/Prescription/AddPrescriptionItem.cshtml
@model WebApp.Models.PrescriptionModels.AddPrescriptionItemViewModel

@{
    ViewData["Title"] = "Dodaj lek do recepty";
}

<h2>Dodawanie leku do recepty</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPrescriptionItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.PrescriptionId)
            <div class="form-group">
                <label asp-for="MedicineList" class="control-label"></label>
                <select asp-for="MedicineId" class="form-control selectpicker" data-live-search="true"
                        asp-items="@{new SelectList(Model.MedicineList,"Id","FullName")}"></select>
                <span asp-validation-for="MedicineId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityToBuy" class="control-label"></label>
                <input asp-for="QuantityToBuy" class="form-control" />
                <span asp-validation-for="QuantityToBuy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>
                    <span>Dodaj</span>
                </button>
            </div>
        </form>
    </div>
</div>

<button onclick="location.href='@Url.Action("PrescriptionDetails","Prescription", new { id = Model.PrescriptionId })'"
        class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span>
    <span>Powrót do recepty</span>
</button>

WebApp/WebApp/Views/Prescription/BuySomeItems.cshtml
@using WebApp.Models.PrescriptionModels;
@model BuySomeItemsViewModel

@{
    ViewData["Title"] = "Kup część recepty";
}

<h2>Kup część recepty</h2>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="BuySomeItems">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.PrescriptionId)
            <div class="form-group">
                <ul class="list-group">
                    @Html.HiddenFor(m => m.PrescriptionId)
                    @for (int i = 0; i < Model.Items.Count; i++)
                    {
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-8">
                                    <h4 class="list-group-item-heading">
                                        @Model.Items[i].MedicineName
                                    </h4>
                                    <div class="form-group">
                                        <label asp-for="Items[i].Amount" class="control-label"></label>
                                        <input id="input-@i" min="0" asp-for="Items[i].Amount" class="form-control" />
                                        <span id="validation-@i" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        @Html.DisplayName("Cena sumaryczna")
                                        <span id="cost-@i"></span>
                                    </div>
                                    @Html.HiddenFor(model => model.Items[i].Available)
                                    @Html.HiddenFor(model => model.Items[i].MedicineName)
                                    @Html.HiddenFor(model => model.Items[i].RemainingAmount)
                                    @Html.HiddenFor(model => model.Items[i].ItemId)
                                    @Html.HiddenFor(model => model.Items[i].UnitPrice)
                                </div>
                                <div class="col-md-4">
                                    <div class="well well-sm">
                                        <div class="form-group">
                                            @Html.DisplayNameFor(model => model.Items[i].RemainingAmount)
                                            @Html.DisplayFor(model => model.Items[i].RemainingAmount)
                                        </div>
                                        <div class="form-group">
                                            @Html.DisplayNameFor(model => model.Items[i].Available)
                                            @Html.DisplayFor(model => model.Items[i].Available)
                                        </div>
                                        <div class="form-group">
                                            @Html.DisplayName("Cena jednostkowa")
                                            @Html.DisplayFor(model => model.Items[i].UnitPrice) zł
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
            <div class="well well-sm">
                <div class="form-group">
                    @Html.DisplayName("Do zapłaty")
                    <span id="cost-span"></span>
                </div>
            </div>
            <div class="form-group">
                <button id="buy_button" type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-shopping-cart"></span>
                    <span>Kup</span>
                </button>
            </div>
        </form>
    </div>
</div>

<button onclick="location.href='@Url.Action("PrescriptionDetails","Prescription", new { id = Model.PrescriptionId })'"
        class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span>
    <span>Powrót do recepty</span>
</button>

<script type="text/javascript">
    $(document).ready(() => {
        let model = @Html.Raw(Json.Serialize(Model));
        let cost = 0.0;
        $("#cost-span").text(cost.toFixed(2).replace(".", ",") +" zł");

        for (let i = 0; i < model.items.length; i++) {
            $("#cost-" + i).text(cost.toFixed(2).replace(".",",") + " zł");
            $("#input-" + i).change(i, updatePrice);
        }

        function updatePrice(e) {
            let id = e.data;
            let items = model.items;

            $("#validation-" + id).text(null);
            let amount = parseInt($("#input-" + id).val());

            let remainingAmount = items[id].remainingAmount;
            if (isNaN(amount)) {
                $("#validation-" + id).text("Wartość nie może być pusta")
            }
            if (amount > remainingAmount) {
                $("#validation-" + id).text(
                    "Nie można kupić " + amount + " sztuk leku, bo pozostało " + remainingAmount + " sztuk do kupienia");
            }

            let localCost = amount * items[id].unitPrice;
            $("#cost-" + id).text(localCost.toFixed(2).replace(".", ",") + " zł");

            updateTotalPrice();
        }

        function updateTotalPrice() {
            let items = model.items;
            let cost = 0.0;

            $("#buy_button").removeAttr("disabled");
            for (let i = 0; i < items.length; i++) {
                cost += parseInt($("#cost-" + i).text());
                if ($("#validation-" + i).text())
                    $("#buy_button").attr("disabled", "disabled");
            }

            if (isNaN(cost)) {
                $("#buy_button").attr("disabled", "disabled");
                $("#cost-span").text(cost.toFixed(2).replace(".", ",") + " zł");
            }
            else {
                $("#cost-span").text(cost.toFixed(2).replace(".", ",") + " zł");
            }
        }
    });



</script>

WebApp/WebApp/Views/Prescription/CreatePrescription.cshtml
@model WebApp.Models.PrescriptionModels.CreatePrescriptionViewModel

@{
    ViewData["Title"] = "Dodaj receptę";
}

<h2>Dodawanie recepty</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePrescription">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DoctorSelect" class="control-label"></label>
                <select asp-for="DoctorId" class="form-control selectpicker" data-live-search="true"
                    asp-items="@{new SelectList(Model.DoctorSelect,"Id","FullName")}"></select>
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApothecarySelect" class="control-label"></label>
                <select asp-for="ApothecaryId" class="form-control selectpicker" data-live-search="true"
                        asp-items="@{new SelectList(Model.ApothecarySelect,"Id","FullName")}"></select>
                <span asp-validation-for="ApothecaryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrescriptionDate" class="control-label"></label>
                <input asp-for="PrescriptionDate" class="form-control" />
                <span asp-validation-for="PrescriptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>
                    <span>Utwórz</span>
                </button>
            </div>
        </form>
    </div>
</div>

<button onclick="location.href='@Url.Action("Index","Prescription")'"
        class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span>
    <span>Powrót</span>
</button>

WebApp/WebApp/Views/Prescription/EditPrescription.cshtml
@model WebApp.Models.PrescriptionModels.CreatePrescriptionViewModel

@{
    ViewData["Title"] = "Edycja recepty";
}

<h2>Edycja recepty numer: @Model.Id </h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPrescription">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DoctorSelect" class="control-label"></label>
                <select asp-for="DoctorId" class="form-control selectpicker" data-live-search="true"
                    asp-items="@{new SelectList(Model.DoctorSelect,"Id","FullName")}"></select>
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApothecarySelect" class="control-label"></label>
                <select asp-for="ApothecaryId" class="form-control selectpicker" data-live-search="true"
                        asp-items="@{new SelectList(Model.ApothecarySelect,"Id","FullName")}"></select>
                <span asp-validation-for="ApothecaryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrescriptionDate" class="control-label"></label>
                <input asp-for="PrescriptionDate" class="form-control" />
                <span asp-validation-for="PrescriptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.Id)
                @Html.HiddenFor(m => m.RowVersion)
                @Html.HiddenFor(m => m.Status)
                @Html.HiddenFor(m => m.TotalCost)
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>
                    <span>Akceptuj</span>
                </button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><span class="glyphicon glyphicon-arrow-left"></span>Powrót</a>
</div>

WebApp/WebApp/Views/Prescription/EditPrescriptonItem.cshtml
@model WebApp.Models.PrescriptionModels.PrescriptionItemViewModel

@{
    ViewData["Title"] = "Edycja leku na recepcie";
}

<h2>Edycja leku na recepcie</h2>

<h4>Lek @Model.Medicine.MedicineContent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPrescriptonItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.MedicineId)
            @Html.HiddenFor(m => m.PrescriptionId)
            @Html.HiddenFor(m => m.RowVersion)
            <div class="form-group">
                <label asp-for="QuantityToBuy" class="control-label"></label>
                <input asp-for="QuantityToBuy" class="form-control" />
                <span asp-validation-for="QuantityToBuy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-ok"></span>
                    <span>Akceptuj</span>
                </button>
            </div>
        </form>
    </div>
</div>

<button onclick="location.href='@Url.Action("PrescriptionDetails","Prescription", new { id = Model.PrescriptionId })'"
        class="btn btn-default">
    <span class="glyphicon glyphicon-arrow-left"></span>
    <span>Powrót do recepty</span>
</button>

WebApp/WebApp/Views/Prescription/Index.cshtml
@using WebApp.Models.PrescriptionModels
@model IndexViewModel

@{
    ViewData["Title"] = "Recepty";
}

<h2>Recepty</h2>

<div class="row">
    <div class="col-md-2">
        <div class="btn-group">
            <button onclick="location.href='@Url.Action("CreatePrescription","Prescription")'" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span>
                <span>Dodaj nową receptę</span>
            </button>
        </div>
    </div>
    <div class="col-md-9">
        <form class="form-inline" asp-action="Search">
            <div class="form-group">
                <label>Wyszukaj receptę</label>
                <input class="form-control" asp-for="SearchId" placeholder="Numer recepty"/>
                <input type="submit" value="Szukaj" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>



<br />

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Prescriptions.First().DoctorFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prescriptions.First().ApothecaryFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prescriptions.First().PrescriptionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prescriptions.First().CompletionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prescriptions.First().Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prescriptions.First().TotalCost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Prescriptions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DoctorFullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApothecaryFullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrescriptionDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompletionDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusString)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalCost)
                </td>
                <td>
                    <div class="btn-group">
                        <button onclick="location.href='@Url.Action("PrescriptionDetails","Prescription", new { id = item.Id })'"
                                class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                            <span>Detale</span>
                        </button>
                        <button onclick="location.href='@Url.Action("DeletePrescription","Prescription", new { id = item.Id })'"
                                class="btn btn-default">
                            <span class="glyphicon glyphicon-remove"></span>
                            <span>Usuń</span>
                        </button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>